### ISSUE TITLE
some clusters in  poiunt cloud after decoding 

### ISSUE THREAD

**Issue by MaybeOjbk** [PRBonn/deep-point-map-compression#1]
I don't know if there are some mistakes  in your code that the  point cloud after decoding have some clusters , 
![image](https://user-images.githubusercontent.com/38483419/122178976-aa844980-ceb9-11eb-9b1e-c85d54f0be52.png)
![image](https://user-images.githubusercontent.com/38483419/122179154-d273ad00-ceb9-11eb-94db-b7c5cab690fd.png)

**Comment by MaybeOjbk** [comment]
or I need to change parameters  which can solve the problem

**Comment by louis-wiesmann** [comment]
Hello @MaybeOjbk,
yes it can happen that point clusters occur. If this is unwanted i suggest either spatially filter them out (e.g. voxelgrid) or try to add an repulsive loss on the points of the output.

**Comment by xbais** [comment]
Hello @louis-wiesmann , do you have any idea as to why the clustering is happening? Can I talk to you on email?

**Comment by louis-wiesmann** [comment]
There is nothing which forbids or punishes the network for creating cluster (as mentioned a repulsive loss could do this). 
But this behavior is not necessarily undesired. In the upsampling process each point creates a couple of other points. The upsampling ratio was computed heuristically and is for each point the same. There is no mechanism to tell a point when to stop the upsampling, so it will create more points but at the same location.

**Comment by louis-wiesmann** [comment]
To get rid of the clusters I used simply grid based subsampling: [from Open3d](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Voxel-downsampling).

**Comment by louis-wiesmann** [comment]
To get rid of the clusters I used simply grid based subsampling: [from Open3d](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Voxel-downsampling).
