### ISSUE TITLE
The Nuscene Dataset

### ISSUE THREAD

**Issue by YYYY1213800** [PRBonn/deep-point-map-compression#10]
Thank for your work @louis-wiesmann. I noticed that you mentioned in your paper that you did a generalization test on the Nuscene dataset, but did not find the corresponding part in the code, I wonder if it is convenient to provide this part.thanks a lot

**Comment by louis-wiesmann** [comment]
As far as I remember (its three years ago xD) I first converted the NuScene dataset into the KITTI format (probably similar to [here)](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py)). Make sure to get all lidar scans and not only the annotated ones. Then I used the script to convert it to the dense submap [here](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/datasets/kitti2voxel.py). 
Please let me know if you need something else.
