### ISSUE TITLE
transfer to a new dataset

### ISSUE THREAD

**Issue by tuning12** [PRBonn/deep-point-map-compression#11]
First thank you for your great work. I have a question about using your model on my dataset.
My trainingset, validset and testingset is three .pkl files with sizes of [B, N, 3] which is normalized already. Could you tell me how to transform my data to the form which could be trained? Thank you so much.

**Comment by louis-wiesmann** [comment]
This version can only handle batch size 1. But you could accumulate gradients for B times and update the weights only after this. This should be equivalent.
