### ISSUE TITLE
Encoded Point Cloud Getting Translated

### ISSUE THREAD

**Issue by ramandika** [PRBonn/deep-point-map-compression#13]
Hey Louis, I get confused by the result, since the translated point cloud (after compression and decompression) get translated from the original one. I think the size is similar, the only problem is that their position differs and somehow the height is also differ from the original one by some height. Any idea about this. I attached an image showing this issue. Possibly because of this class?

```python
class Normalizer():
    def __init__(self, data, dif=None):
        self.min = np.amin(data, axis=0, keepdims=True)
        self.max = np.amax(data, axis=0, keepdims=True)
        if dif is None:
            self.dif = self.max-self.min
        else:
            self.dif = dif

    def getScale(self):
        return self.dif

    def normalize(self, points):
        return (points - self.min)/self.dif

    def recover(self, norm_points):
        return (norm_points * self.dif)+self.min
```

![image](https://github.com/PRBonn/deep-point-map-compression/assets/7370645/a57c195e-18b5-4b95-8e97-fb512bbad2be)

**Comment by louis-wiesmann** [comment]
Hey @ramandika,

I checked and it the function it self should work:
![image](https://github.com/PRBonn/deep-point-map-compression/assets/76427549/83328b34-dfee-40e9-a6a2-60b3700dbd52)

Be aware that you need to use the same normalizer. If you initialize one on the original data it will have the proper scale and offset. If you then for recovering initialize a normalizer on the normalized data it will have the wrong offset and scale.
