### ISSUE TITLE
Have you tried add the symmetric plane distance to the loss

### ISSUE THREAD

**Issue by ZorAttC** [PRBonn/deep-point-map-compression#14]
As I can see the upsamlping result of the encoded pointcloud is somehow noisy，e.g. the ground points should be lying on the ground  neatly but actually it shifts a lot and seems noisy.I want to know have you guys tried to add the the symmetric plane distance to the loss? (it seems that it will help these points to lie on the same ground)

**Comment by louis-wiesmann** [comment]
Hey @ZorAttC, yes I agree that this could improve the network quite a bit. Probably even precomputing the normals and adding them could already help. We didn't do it since we did not want to be reliable on the normal computation.

**Comment by ZorAttC** [comment]
haha,is computing the normals a heavy burden?it doesn't involve in the forward stage ,so it may not get the encoder and decoder to get slower.

**Comment by louis-wiesmann** [comment]
I agree 100% . In comparison to run a convolutional neural network its no effort at all. And nowadays I would probably also go for it.

**Comment by ZorAttC** [comment]
@louis-wiesmann Thx for your immediate reply,it really helps!
