### ISSUE TITLE
Cannot Install `octree_handler` on Google Colab

### ISSUE THREAD

**Issue by xbais** [PRBonn/deep-point-map-compression#3]
Hello.
I am trying to  run the code on Google Colab. While trying to install the third party dependency (following the instructions given in the [Dockerfile](https://github.com/PRBonn/deep-point-map-compression/blob/main/Dockerfile)) `octree_handler` via the command:

`cd depoco/submodules/octree_handler && pip3 install -U .`

...I get the following error:
```
Processing /content/git-clone/submodules/octree_handler
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: octree-handler
  Building wheel for octree-handler (setup.py) ... error
  ERROR: Failed building wheel for octree-handler
  Running setup.py clean for octree-handler
Failed to build octree-handler
Installing collected packages: octree-handler
    Running setup.py install for octree-handler ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7l37y9ju/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7l37y9ju/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qzusj2ky/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/octree-handler Check the logs for full command output.
```

**Comment by jokieleung** [comment]
same issue...any solution now?

**Comment by xbais** [comment]
The issue is somewhere with `pybind11-dev` apt package getting installed in the Colab runtime.

Doing :
`!pip install "pybind11[global]"`
...instead of :
`!sudo apt install pybind11-dev`
...and then proceeding with the usual steps works for me....(for now).

(Refer : https://github.com/hfutcgncas/normalSpeed/issues/3)

**Comment by aakashsinghbais** [comment]
The issue is somewhere with `pybind11-dev` apt package getting installed in the Colab runtime.

Doing :
`!pip install "pybind11[global]"`
...instead of :
`!sudo apt install pybind11-dev`
works for me....(for now).

(Refer : https://github.com/hfutcgncas/normalSpeed/issues/3)
