### ISSUE TITLE
Large Layered Clusters in Output Clouds Obtained from the Decoder.

### ISSUE THREAD

**Issue by xbais** [PRBonn/deep-point-map-compression#4]
Hello @louis-wiesmann .
After training the model to at the default params with `epochs=15`, I am using the trained model to test the results on a sample point cloud.

The input cloud I used for testing when looked from side looks like this :
![image](https://user-images.githubusercontent.com/56718090/157007156-c12fe44e-f706-4be5-9c5c-052e5b62daaa.png)

On the other hand, the output obtained from the decoder looks like this:
![image](https://user-images.githubusercontent.com/56718090/157007275-aa18af9f-c6a6-4b40-8e0e-187cb5087453.png)

As is clearly visible, the output from the decoder has a somewhat layered structure. Is there any way to minimize this / correct this?

Some other info:
1. Total points in the original cloud = 11,000,000
2. `max_nr_points` (set in the yaml file) = 60,000

<hr>

Also, I am getting some big clusters in the outputs that I get from the decoder...as can be seen in sample outputs below : 
<table><tr><th>Input Cloud</th><th>Output Cloud</th></tr>
<tr><td><img src="https://user-images.githubusercontent.com/56718090/157112989-ab4367e3-7b57-4c4c-8263-39db43d585da.png"></td><td><img src="https://user-images.githubusercontent.com/56718090/157121548-8340992a-2427-4919-8420-0ffc1df96ae0.png"></td></tr>
<tr><td><img src="https://user-images.githubusercontent.com/56718090/157110878-26be1e8b-1254-4216-a0bd-82717198a110.png"></td><td><img src="https://user-images.githubusercontent.com/56718090/157118853-62077b65-5d4d-4262-a3c5-ccc5e3bed1ca.png"></td></tr></table>

Can you please tell if there is any parameter that can be tweaked in the YAML config file to get rid of this layered clustering. Or is there any other way to minimize or eliminate this ? 

> NOTE : I have already seen the other issue on clustering, but in my case the clusters seem to be large.

Thanks

**Comment by louis-wiesmann** [comment]
Hello @aakashsinghbais,

The figures look like that it requires more training. 15 epochs looks quite few (we used 200 for the paper). The network is probably learning first to reconstruct horizontal planes, due to the very high proportion of horizontal planes in the data (I would guess over 80% of the points belong to streets, ground, or roofs).

Best,
Louis
