### ISSUE TITLE
Retaining Labels in the Output Clouds from Decoder

### ISSUE THREAD

**Issue by xbais** [PRBonn/deep-point-map-compression#7]
Hello @louis-wiesmann . Is there any way to retain the class labels of the points obtained after decompression from the decoder?

Thanks in advance.
Aakash

**Comment by louis-wiesmann** [comment]
Hey, if you mean labels like the ones in SemanticKittti (e.g. Car, Person,Street....)  then not without modification. The input are only the point cloud, without attributes. But you could modify the code. Instead of initializing the features with ones; simply use the attributes. In the end you would need to output also features which should correspond to the attributes (for labels one hot encoding might be better) and have a second loss term to optimize for attribute quality.

**Comment by xbais** [comment]
Hello @louis-wiesmann , can you please direct me to the exact places in the code that will require changes. This will help me a lot!

**Comment by louis-wiesmann** [comment]
The features of the last decoding are not really used. I used them as a last translation vector [here](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/trainer.py#L189). But this could be your features (e.g. a one hot encoding).
For this you would need to set the out_dim to the number of classes you have [here](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/config/depoco.yaml#L103).
The same you have to do for the input: either return the label as first feature or the onehot encoding (am not a segmentation person, so dont know what would work best...), change the [config](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/config/depoco.yaml#L63) accordingly.
For returning the labels you have to modify something around [here](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/datasets/submap_handler.py#L203).
But im currently unaware if the labels are even saved in the submaps, but you will figure out.

You would need to create a third loss to optimize for the features, add [here](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/trainer.py#L201).

**Comment by xbais** [comment]
Thanks a lot! I will implement the changes and come back to you in a while if I face issues...

**Comment by Master-cai** [comment]
> Thanks a lot! I will implement the changes and come back to you in a while if I face issues...

hi, I am very interested in your idea. Have you implemented it? How does it work?
