### ISSUE TITLE
Failed to build chamfer-3D

### ISSUE THREAD

**Issue by YYYY1213800** [PRBonn/deep-point-map-compression#9]
Hello @louis-wiesmann 
when I install the 3rdparty dependencies, I meet the problem:
ERROR [12/13] RUN cd depoco/submodules/ChamferDistancePytorch/chamfer3D/ && pip3 install -U . 2>/dev/null
I guess what matters is the setup process for chamfer-3D,the details are:
Building wheels for collected packages: chamfer-3D
#0 1.824   Building wheel for chamfer-3D (setup.py): started
#0 2.682   Building wheel for chamfer-3D (setup.py): finished with status 'error'
#0 2.682   Running setup.py clean for chamfer-3D
#0 3.509 Failed to build chamfer-3D
#0 4.069 Installing collected packages: chamfer-3D
#0 4.069     Running setup.py install for chamfer-3D: started
#0 4.940     Running setup.py install for chamfer-3D: finished with status 'error'
is there any way to solve the problem?
thanks in advance

**Comment by louis-wiesmann** [comment]
Hello @YYYY1213800,
unfortunately this library is not maintained by us. I will investigate further in this as soon as i have time!

**Comment by YYYY1213800** [comment]
thanks a lot .I think I have solved the problem. Some versions are in conflict.

**Comment by louis-wiesmann** [comment]
Okay thank you. If you tell me which ones I can have a look and update the repo probably.

**Comment by aprilbian** [comment]
I have the same question, could you please tell me how to resolve this?

**Comment by YYYY1213800** [comment]
@louis-wiesmann  I think this problem is caused by a mismatch between the computational power requirements of my computer with the torch version,So I added computational power constraints to bashrc and it works。@aprilbian maybe you can solve the problem in this way

**Comment by YYYY1213800** [comment]
@louis-wiesmann By the way,I have noticed that there is a performance test for the Nuscene dataset in the paper, and I want to reproduce this result. Could you please provide me with code on Nuscene data processing? I downloaded the Nuscene mini dataset, but it's structure is quite different from the semantic kitti.
It doesn't matter if it's inconvenient to provide。
Thanks a lot

**Comment by yn10828** [comment]
> @louis-wiesmann I think this problem is caused by a mismatch between the computational power requirements of my computer with the torch version,So I added computational power constraints to bashrc and it works。@aprilbian maybe you can solve the problem in this way

What should be done specifically？
